### ISSUE TITLE
General

### ISSUE THREAD

**Issue by wuestenarchitekten** [TouchDesigner/Palette#2]
- [x] Add in Help Component to all Palette Items
- [x] If Palette Components are Container, make sure the Display Parameter is turned off
- [x] when saving out components, make sure your Preferences are set to "Resize TOP Nodes to TOP Viewer Aspect" as well as "Resize Panel COMP Nodes to ControlPanel Aspect", then reset node sizes
- [x] make sure the pane is homed before saving out the tox

**Comment by brvoigt** [comment]
For all palette COMPs that got the docsHelper added, reposition it so it is closer to the network of nodes in the same location each time. We want it close so that when you 'home' the network, you get the best view possible of the network, when it is far away the network will be tiny. See atttached examples

- [ ] Position docHelper in all COMPs

![54188873-fd5d4280-44f3-11e9-8a98-f184dbdb693a](https://user-images.githubusercontent.com/8110813/54189317-e3702f80-44f4-11e9-9435-1c52e157a8f9.png)
![54188872-fd5d4280-44f3-11e9-8d66-6623ea66f615](https://user-images.githubusercontent.com/8110813/54189319-e3702f80-44f4-11e9-8847-7f79122248cd.png)
